### ISSUE TITLE
Once built a project...

### ISSUE THREAD

**Issue by maiorfi** [Seeed-Studio/CodeLite_for_RePhone#1]
...how to upload elf file to device?

**Comment by xiongyihui** [comment]
We use vxp file instead. Hold the RePhone's button 2 seconds to enter storage mode. The RePhone will act as a USB Storage. Put the vxp file into the storage and edit the file named `autostart.txt` (create one if not existed).  The content of the `autostart.txt` is like:

```
[autostart]
App=C:\your_app_name.vxp
```

**Comment by xiongyihui** [comment]
Maybe you can refer to the guide - http://www.seeedstudio.com/wiki/Lua_for_RePhone
