### ISSUE TITLE
How to see the output of vm_log_info?

### ISSUE THREAD

**Issue by ghost** [Seeed-Studio/CodeLite_for_RePhone#2]
I've successfully make the example, project_blink. And the green led is blinking every 1 second.
In the code there is a debug code which is using vm_log_info. Where this debug output is?

**Comment by xiongyihui** [comment]
Monitor.exe in the Linkit Assist 2502 SDK is used to view the log.

There is a python version written by mandl - https://github.com/mandl/LinkIt_Assist_2502
